spring:
  datasource:
    url: jdbc:mysql://localhost:3306/breath?useSSL=false
    username: breath
    password: breath
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

---